<?php if($this->helper('Maximizly\Webpush\Helper\Data')->getConfig('webpush/general/enable')): ?>

    <?php $viewModel = $block->getViewModel(); ?>

    <script>
        document.addEventListener('DOMContentLoaded', function() {
            maximizly.push([
                'trackEcommerceOrder',
                "<?= $viewModel->getOrderNumber() ?>",
                <?= $viewModel->getOrderTotal() ?>,
                <?= $viewModel->getCurrency() ?>
            ]);
        });
    </script>

<?php endif; ?>
