<?php if($this->helper('Maximizly\Webpush\Helper\Data')->getConfig('webpush/general/enable')): ?>
    <!-- Maximizly Module enabled -->
    <script>
        let maximizly = []; maximizly['webpush_domain'] = '<?= $this->helper('Maximizly\Webpush\Helper\Data')->getConfig('webpush/general/domain'); ?>';
    </script>
    <script src="https://maximizly.s3.eu-central-1.amazonaws.com/sources/webpush/develop/js/maximizly-push.js"></script>
<?php else: ?>
<!-- Maximizly Module disabled -->
<?php endif; ?>